stages:
  data_generation:
    cmd: python synthetic_generator.py
    deps:
    - Data/personality_datasert.csv
    - synthetic_generator.py
    outs:
    - Data/synthetic_ctgan_data.csv
    metrics:
    - Data/synthetic_data_metrics.json
    
  data_validation:
    cmd: python scripts/check_data_drift.py
    deps:
    - Data/personality_datasert.csv
    - Data/synthetic_ctgan_data.csv
    - scripts/check_data_drift.py
    outs:
    - drift_report.json
    - drift_status.txt
    
  model_training:
    cmd: python train_with_mlflow.py
    deps:
    - Data/synthetic_ctgan_data.csv
    - train_with_mlflow.py
    outs:
    - Model/personality_classifier.joblib
    - Model/label_encoder.joblib
    - Model/feature_names.json
    metrics:
    - Model/training_metrics.json
    
  model_evaluation:
    cmd: python evaluate_model.py
    deps:
    - Model/personality_classifier.joblib
    - Model/label_encoder.joblib
    - Data/synthetic_ctgan_data.csv
    - evaluate_model.py
    outs:
    - Results/confusion_matrix.png
    - Results/feature_importance.png
    - Results/roc_curve.png
    - Results/class_distribution.png
    metrics:
    - Results/evaluation_report.json
